In [65]:
# Import Dependencies
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

In [106]:
# Store filepath in a variable
dataset_csv = "./dataset_immigrantstat.csv"
immigrant_stat_df = pd.read_csv(dataset_csv)
immigrant_stat_df

,Regions,Geographic area type abbreviation,Province or territory abbreviation,Total,Non_immigrants,Total_Immigrants,Non_PR_residents,Before_2001,2001_to_2005,2006_to_2010,2011_to_2015,2016_to_2021
0,Barrie,CMA,Ont.,"210,155","171,400",35340,3405,20395,3465,3545,3780,4160
1,Belleville - Quinte West,CMA,Ont.,"109,245","99,070",9065,1115,6040,730,740,685,870
2,Brantford,CMA,Ont.,"141,905","120,245",20235,1430,12485,1735,1855,1885,2265
3,Brockville,CA,Ont.,"30,880","27,930",2855,95,2075,155,200,165,260
4,Centre Wellington,CA,Ont.,"30,645","27,085",3450,110,2615,215,225,175,220
5,Chatham-Kent,CA,Ont.,"102,090","92,315",9245,530,6290,830,690,585,845
6,Cobourg,CA,Ont.,"19,780","17,190",2550,40,2080,100,75,105,195
7,Collingwood,CA,Ont.,"24,270","20,945",3205,120,2340,215,215,160,285
8,Cornwall,CA,Ont.,"59,750","54,655",4525,570,2490,455,450,475,655
9,Elliot Lake,CA,Ont.,"11,225","10,030",1175,15,1090,35,15,15,25
10,Essa,CA,Ont.,"22,785","20,005",2685,100,1730,220,285,230,220
11,Greater Sudbury,CMA,Ont.,"167,615","154,070",9985,3560,5915,545,765,1115,1655
12,Guelph,CMA,Ont.,"163,485","123,670",37100,2715,18975,3945,3700,4480,6000
13,Hamilton,CMA,Ont.,"773,440","561,180",197845,14410,113205,18735,19545,19820,26545
14,Hawkesbury,CA,Ont. / Que.,"11,640","10,980",625,35,300,35,100,75,120
15,Hawkesbury (Ontario part),CA,Ont.,"9,830","9,215",580,35,290,30,70,75,115
16,Hawkesbury (Quebec part),CA,Que.,"1,815","1,770",50,0,0,10,25,0,0
17,Ingersoll,CA,Ont.,"13,545","12,485",1030,30,715,100,60,40,115
18,Kawartha Lakes,CA,Ont.,"77,230","70,930",6100,195,5125,285,260,220,215
19,Kenora,CA,Ont.,"14,610","13,855",640,115,445,20,45,50,75
20,Kingston,CMA,Ont.,"168,075","144,460",20290,3320,12370,1705,1770,1725,2725
21,Kitchener - Cambridge - Waterloo,CMA,Ont.,"568,065","399,240",146575,22250,70490,15300,16195,16810,27785
22,London,CMA,Ont.,"535,780","400,620",115600,19555,58715,10155,12180,14055,20495
23,Midland,CA,Ont.,"26,365","24,020",2265,80,1620,160,160,140,180
24,Norfolk,CA,Ont.,"66,225","58,905",7075,240,5420,390,475,285,520
25,North Bay,CA,Ont.,"70,175","66,260",3375,540,2310,210,295,250,315
26,Orillia,CA,Ont.,"32,270","28,970",3115,185,2235,195,215,200,280
27,Oshawa,CMA,Ont.,"411,405","315,710",91815,3880,51185,9755,9720,9600,11555
28,Ottawa - Gatineau,CMA,Ont. / Que.,"1,464,495","1,115,495",313845,35160,144720,33350,37185,40295,58295
29,Ottawa - Gatineau (Ontario part),CMA,Ont.,"1,116,795","819,940",267060,29800,129360,27750,29730,32050,48170
30,Ottawa - Gatineau (Quebec part),CMA,Que.,"347,700","295,560",46785,5360,15355,5600,7455,8245,10125
31,Owen Sound,CA,Ont.,"31,875","29,410",2340,125,1620,155,140,100,320
32,Pembroke,CA,Ont.,"23,085","22,060",970,55,705,40,85,65,75
33,Petawawa,CA,Ont.,"17,295","16,130",1065,100,500,130,150,155,130
34,Peterborough,CMA,Ont.,"125,995","113,400",10975,1615,7295,865,720,790,1300
35,Port Hope,CA,Ont.,"16,885","15,150",1720,20,1505,90,55,40,25
36,Sarnia,CA,Ont.,"96,285","84,845",10080,1360,7420,575,670,640,775
37,Sault Ste. Marie,CA,Ont.,"75,420","68,400",6095,925,4655,255,270,330,590
38,St. Catharines - Niagara,CMA,Ont.,"425,480","340,945",76305,8235,49435,6060,6410,6175,8225
39,Stratford,CA,Ont.,"32,480","28,625",3560,300,2495,175,230,235,415
40,Thunder Bay,CMA,Ont.,"120,960","108,275",9980,2710,7095,440,710,630,1100
41,Tillsonburg,CA,Ont.,"18,300","15,980",2295,15,1805,95,165,135,105
42,Timmins,CA,Ont.,"40,310","38,290",1370,650,805,85,95,145,250
43,Toronto,CMA,Ont.,"6,142,885","3,030,050",2862850,249980,1457075,362720,326680,324700,391685
44,Wasaga Beach,CA,Ont.,"24,585","20,170",4275,140,3710,195,110,120,150
45,Windsor,CMA,Ont.,"415,505","309,345",96910,9255,51460,8810,9545,11265,15830
46,Woodstock,CA,Ont.,"45,950","38,855",6805,285,3670,550,800,835,950

In [67]:
# Create a DataFrame with columns to total: Before 2001, 2001 to 2005, 2006 to 2010, 
# 2011 to 2015, 2016 to 2021, Non-immigrants, Immigrants, Non-PR residents 

immigrant_total_df = immigrant_stat_df[['Regions', 'Total_Immigrants',
                                        'Before_2001', '2001_to_2005', '2006_to_2010', 
                                         '2011_to_2015', '2016_to_2021']]
immigrant_total_df.head()

,Regions,Total_Immigrants,Before_2001,2001_to_2005,2006_to_2010,2011_to_2015,2016_to_2021
0,Barrie,35340,20395,3465,3545,3780,4160
1,Belleville - Quinte West,9065,6040,730,740,685,870
2,Brantford,20235,12485,1735,1855,1885,2265
3,Brockville,2855,2075,155,200,165,260
4,Centre Wellington,3450,2615,215,225,175,220

In [68]:
# Region name
Region_name = immigrant_stat_df.set_index(["Regions"]).groupby(["Regions"])
Region_name

In [69]:
# Calculate the total number of Regions in Ontario
Region_count = len(immigrant_stat_df["Total "].unique())
Region_count

47

In [123]:
Per_Region_count = immigrant_stat_df.set_index("Regions")["Total_Immigrants"]
Per_Region_count

Regions
Barrie                                 35340
Belleville - Quinte West                9065
Brantford                              20235
Brockville                              2855
Centre Wellington                       3450
Chatham-Kent                            9245
Cobourg                                 2550
Collingwood                             3205
Cornwall                                4525
Elliot Lake                             1175
Essa                                    2685
Greater Sudbury                         9985
Guelph                                 37100
Hamilton                              197845
Hawkesbury                               625
Hawkesbury (Ontario part)                580
Hawkesbury (Quebec part)                  50
Ingersoll                               1030
Kawartha Lakes                          6100
Kenora                                   640
Kingston                               20290
Kitchener - Cambridge - Waterloo      146575
London                                115600
Midland                                 2265
Norfolk                                 7075
North Bay                               3375
Orillia                                 3115
Oshawa                                 91815
Ottawa - Gatineau                     313845
Ottawa - Gatineau (Ontario part)      267060
Ottawa - Gatineau (Quebec part)        46785
Owen Sound                              2340
Pembroke                                 970
Petawawa                                1065
Peterborough                           10975
Port Hope                               1720
Sarnia                                 10080
Sault Ste. Marie                        6095
St. Catharines - Niagara               76305
Stratford                               3560
Thunder Bay                             9980
Tillsonburg                             2295
Timmins                                 1370
Toronto                              2862850
Wasaga Beach                            4275
Windsor                                96910
Woodstock                               6805
Name: Total_Immigrants, dtype: int64

In [70]:
# Calculate the total number of immigrants in Ontario till 2021
immigrant_count = immigrant_stat_df["Total_Immigrants"].sum()
immigrant_count

4463680

In [107]:
average_before_2001 = immigrant_stat_df.groupby(["Regions"]).mean()["Before_2001"]
average_before_2001.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_4340\1412515660.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_before_2001 = immigrant_stat_df.groupby(["Regions"]).mean()["Before_2001"]

Regions
Barrie                       20395.0
Belleville - Quinte West      6040.0
Brantford                    12485.0
Brockville                    2075.0
Centre Wellington             2615.0
Name: Before_2001, dtype: float64

In [108]:
average_2001_to_2005 = immigrant_stat_df.groupby(["Regions"]).mean()["2001_to_2005"]
average_2001_to_2005.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_4340\1738160188.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_2001_to_2005 = immigrant_stat_df.groupby(["Regions"]).mean()["2001_to_2005"]

Regions
Barrie                       3465.0
Belleville - Quinte West      730.0
Brantford                    1735.0
Brockville                    155.0
Centre Wellington             215.0
Name: 2001_to_2005, dtype: float64

In [109]:
average_2006_to_2010 = immigrant_stat_df.groupby(["Regions"]).mean()["2006_to_2010"]
average_2006_to_2010.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_4340\1415694324.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_2006_to_2010 = immigrant_stat_df.groupby(["Regions"]).mean()["2006_to_2010"]

Regions
Barrie                       3545.0
Belleville - Quinte West      740.0
Brantford                    1855.0
Brockville                    200.0
Centre Wellington             225.0
Name: 2006_to_2010, dtype: float64

In [110]:
average_2011_to_2015 = immigrant_stat_df.groupby(["Regions"]).mean()["2011_to_2015"]
average_2011_to_2015.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_4340\2523827086.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_2011_to_2015 = immigrant_stat_df.groupby(["Regions"]).mean()["2011_to_2015"]

Regions
Barrie                       3780.0
Belleville - Quinte West      685.0
Brantford                    1885.0
Brockville                    165.0
Centre Wellington             175.0
Name: 2011_to_2015, dtype: float64

In [104]:
average_2016_to_2021 = immigrant_stat_df.groupby(["Regions"]).mean()["2016_to_2021"]
average_2016_to_2021.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_4340\989522850.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_2016_to_2021 = immigrant_stat_df.groupby(["Regions"]).mean()["2016_to_2021"]

Regions
Barrie                       4160.0
Belleville - Quinte West      870.0
Brantford                    2265.0
Brockville                    260.0
Centre Wellington             220.0
Name: 2016_to_2021, dtype: float64

In [114]:
# Calculate the number of immigrants per region before 2001 with 100,000 or higher immigrants
Immigrant_Before_2001 = immigrant_stat_df[immigrant_stat_df["Before_2001"] >= 100000]
Region_Immigrant_Before_2001 = Immigrant_Before_2001.groupby(["Regions"]).count()["Before_2001"]

In [115]:
# Calculate the number of immigrants per region from 2001 to 2005 with 100,000 or higher immigrants
Immigrant_2001_to_2005 = immigrant_stat_df[immigrant_stat_df["2001_to_2005"] >= 100000]
Region_Immigrant_2001_to_2005 = Immigrant_2001_to_2005.groupby(["Regions"]).count()["2001_to_2005"]

In [116]:
# Calculate the number of immigrants per region from 2006 to 2010 with 100,000 or higher immigrants
Immigrant_2006_to_2010 = immigrant_stat_df[immigrant_stat_df["2006_to_2010"] >= 100000]
Region_Immigrant_2006_to_2010 = Immigrant_2006_to_2010.groupby(["Regions"]).count()["2006_to_2010"]

In [117]:
# Calculate the number of immigrants per region from 2011 to 2015 with 100,000 or higher immigrants
Immigrant_2011_to_2015 = immigrant_stat_df[immigrant_stat_df["2011_to_2015"] >= 100000]
Region_Immigrant_2011_to_2015 = Immigrant_2011_to_2015.groupby(["Regions"]).count()["2011_to_2015"]

In [119]:
# Calculate the number of immigrants per region from 2011 to 2015 with 100,000 or higher immigrants
Immigrant_2016_to_2021 = immigrant_stat_df[immigrant_stat_df["2016_to_2021"] >= 100000]
Region_Immigrant_2016_to_2021 = Immigrant_2016_to_2021.groupby(["Regions"]).count()["2016_to_2021"]

In [ ]:
# Use the provided code to calculate the overall immigration rates
per_region_immigration_Before_2001 = Region_Immigrant_Before_2001 / Per_Region_count * 100
per_region_immigration_2001_to_2005 = Region_Immigrant_2001_to_2005 / Per_Region_count * 100
per_region_immigration_2006_to_2010 = Region_Immigrant_2006_to_2010 / Per_Region_count * 100
per_region_immigration_2011_to_2015 = Region_Immigrant_2011_to_2015 / Per_Region_count * 100
per_region_immigration_2016_to_2021 = Region_Immigrant_2016_to_2021 / Per_Region_count * 100
overall_Immigration_rate = school_students_passing_math_and_reading/ Per_Region_count * 100

In [ ]:
# Create a DataFrame called `per_year_summary` with columns for the calculations above.
per_year_summary = pd.DataFrame({"Regions" : Regions,
                                  "Total Students" : per_school_counts,
                                  "Total School Budget" : per_school_budget,
                                  "Per Student Budget" : per_school_capita,
                                  "Average Math Score" : per_school_math,
                                  "Average Reading Score": per_school_reading,
                                  "% Passing Math" : per_school_passing_math,
                                  "% Passing Reading": per_school_passing_reading,
                                  "% Overall Passing": overall_passing_rate})

# Formatting
per_year_summary["Total School Budget"] = per_year_summary["Total School Budget"].map("${:,.2f}".format)
per_year_summary["Per Student Budget"] = per_year_summary["Per Student Budget"].map("${:,.2f}".format)
per_year_summary.index.name = None

# Display the DataFrame
per_year_summary